spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blackboard
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    initialization-mode: always
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    generate-ddl: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    org.springframework.security: DEBUG
custom:
  strings:
    welcome: Welcome to Blackboard, ${custom.strings.name}
    name: Jiseong
mybatis:
  type-aliases-package: kjs.Blackboard